In [1]:
import sys
import os
import pandas as pd
import numpy as np

# Obtener el directorio actual
current_directory = os.getcwd()

# Subir dos niveles al directorio raíz, donde se encuentra la carpeta 'interpretml'
root_path = os.path.abspath(os.path.join(current_directory, '..', '..', '..'))

sys.path.append(root_path)

# Iris Dataset

In [2]:
iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)
iris.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

# Create a binary problem
iris['species'] = np.where(iris['species'] == 'Iris-setosa', 1, 0)

X = iris.drop('species', axis=1)
y = iris['species']

# Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# LDA

In [3]:
import pandas as pd
import numpy as np
from interpret import show
from interpret.glassbox._lineardiscriminantanalysis import LinearDiscriminantAnalysisClassifier

In [4]:
lda = LinearDiscriminantAnalysisClassifier()

In [5]:
lda.fit(X_train, y_train)

In [6]:
lda_local = lda.explain_local(X_test[:3], y_test[:3])
show(lda_local)

[6.1 2.8 4.7 1.2]
-18.125835332866366
[13.835606006162982 36.7887274888782 -49.83205057654085 -4.073418368762643]

[5.7 3.8 1.7 0.3]
-18.125835332866366
[12.928353153299836 49.927558734906135 -18.024358719174348
 -1.0183545921906607]

[7.7 2.6 6.9 2.3]
-18.125835332866366
[17.464617417615568 34.160961239672616 -73.15769127194295
 -7.8073852067950655]



<!-- http://127.0.0.1:7001/2582769738560/ -->