In [1]:
import sys
import os

# Obtener el directorio actual
current_directory = os.getcwd()

# Subir dos niveles al directorio raíz, donde se encuentra la carpeta 'interpretml'
root_path = os.path.abspath(os.path.join(current_directory, '..', '..', '..'))

sys.path.append(root_path)

In [2]:
import pandas as pd
import numpy as np
import interpret
from interpret import show

In [3]:
iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)
iris.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

# Create a binary problem
iris['species'] = np.where(iris['species'] == 'Iris-setosa', 1, 0)

X = iris.drop('species', axis=1)
y = iris['species']

# Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
# import linear from interpret
from interpret.glassbox._naivebayes import NaiveBayesClassifier
from interpret.glassbox._linear import LogisticRegression

nb = NaiveBayesClassifier()
nb.fit(X_train, y_train)

lr = LogisticRegression()
lr.fit(X_train, y_train)

In [5]:
print(X_test.shape)
X_test.sample(3)

(30, 4)


sepal_length  sepal_width  petal_length  petal_width
68            6.2          2.2           4.5          1.5
143           6.8          3.2           5.9          2.3
55            5.7          2.8           4.5          1.3

In [6]:
nb.predict(X_test)

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [7]:
print(nb._model().theta_)
print(nb._model().var_)

[[6.21875 2.86625 4.865   1.6525 ]
 [4.99    3.44    1.4525  0.2425 ]]
[[0.44427344 0.10923594 0.663775   0.17599375]
 [0.1239     0.1549     0.03299375 0.01144375]]


In [8]:
nb_local = nb.explain_local(X_test, y_test)
show(nb_local)

Instance 0
[0.58910469 1.18304806 0.47972598 0.53152785] [7.85226588e-03 2.70199671e-01 8.54819833e-70 1.49645907e-17]
[  4.31780177   1.47668828 158.30069575  38.1088452 ]

Instance 1
[4.42136424e-01 2.23111549e-02 2.58741652e-04 5.26212514e-03] [0.1482137  0.66712011 0.86803717 3.22767017]
[ 1.09296331 -3.39788333 -8.11815973 -6.41898088]

Instance 2
[0.05066118 0.87258711 0.02163416 0.28898043] [1.52440049e-013 1.03928805e-001 1.08398870e-195 1.75343593e-080]
[ 26.52940964   2.1277564  445.0899638  182.40383387]

Instance 3
[0.56714814 1.2007787  0.44291095 0.89015793] [1.84733798e-02 3.95460971e-01 1.65173134e-61 3.68179533e-30]
[  3.42428977   1.11067345 139.14148009  67.65779591]

Instance 4
[0.40921675 1.18304806 0.48810972 0.79340832] [2.05437168e-06 2.70199671e-01 3.90299703e-74 1.40787766e-25]
[ 12.2020302    1.47668828 168.31233709  56.99112668]

Instance 5
[2.81473551e-01 3.27645228e-01 9.67434854e-05 1.10299914e-02] [0.57512496 1.00841985 2.12248571 1.26160337]
[-0.7145488

<!-- http://127.0.0.1:7545/2059603632816/ -->

In [9]:
lr.predict(X_test)

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [10]:
lr_local = lr.explain_local(X_test, y_test)
show(lr_local)

<!-- http://127.0.0.1:7545/2059896444192/ -->