In [6]:
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression

In [3]:
gnb = GaussianNB()
gnb._estimator_type

'classifier'

In [ ]:
import numpy as np

X = np.random.rand(100, 10)
y = np.random.randint(0, 2, 100)

gnb = GaussianNB()
log = LogisticRegression()

gnb.fit(X, y)
log.fit(X, y)

print(gnb.classes_)
print(log.classes_)

[0 1]
[0 1]


In [43]:
log.coef_

array([[ 0.67429415, -0.2721339 ,  0.21561264, -0.30620245,  0.48517748,
        -0.09931777, -0.07518169,  0.7667796 ,  0.95400202,  0.65502925]])

In [46]:
X_test = np.random.rand(5, 10)
print(gnb.predict(X_test))
print(gnb.predict_proba(X_test))

[0 1 1 1 0]
[[0.55763233 0.44236767]
 [0.22394257 0.77605743]
 [0.39028636 0.60971364]
 [0.41620675 0.58379325]
 [0.56376865 0.43623135]]


In [47]:
predictions = gnb.predict_proba(X_test)
print(predictions[:, 1])

[0.44236767 0.77605743 0.60971364 0.58379325 0.43623135]


In [52]:
log.coef_

array([[ 0.67429415, -0.2721339 ,  0.21561264, -0.30620245,  0.48517748,
        -0.09931777, -0.07518169,  0.7667796 ,  0.95400202,  0.65502925]])

In [54]:
np.array([np.log(predictions[:, 0] / predictions[:, 1])])[0]

array([ 0.23155846, -1.24283688, -0.44610869, -0.33836478,  0.25647124])

In [56]:
log.predict_log_proba(X_test)

array([[-0.56622337, -0.83855513],
       [-0.84359374, -0.56240291],
       [-0.83881636, -0.56602446],
       [-0.78282833, -0.61085099],
       [-0.57776391, -0.8236016 ]])

In [71]:
X = np.random.rand(100, 10)
y = np.random.randint(0, 2, 100)

gnb = GaussianNB()

gnb.fit(X, y)

print(gnb.theta_)
print(gnb.var_)

print("\nConditional Probs\n")

X_test = np.random.rand(5, 10)

def conditional_probability(x, mean, std):
    return np.exp(-0.5 * ((x - mean) ** 2) / (std ** 2)) / (np.sqrt(2 * np.pi) * std)

print(conditional_probability(X_test[0, :], gnb.theta_[0, 0], gnb.var_[0, 0]))

[[0.50277861 0.41932677 0.46540686 0.54655665 0.5482016  0.49164485
  0.47667622 0.51231089 0.42408312 0.49144001]
 [0.5101512  0.49917175 0.44336234 0.52715347 0.57629729 0.54081003
  0.45306775 0.5429204  0.42744623 0.45770278]]
[[0.07428148 0.0582953  0.07778554 0.07597123 0.09587576 0.09296941
  0.09321253 0.07325799 0.07934904 0.08302035]
 [0.08169699 0.08470538 0.0910714  0.07452556 0.07118075 0.10749206
  0.09649118 0.07447236 0.09229395 0.08876579]]

Conditional Probs

[1.17261334e-02 8.48369129e-09 1.42360060e-04 1.20110095e+00
 2.40631500e-07 1.03300357e-04 1.58393371e-03 1.08649866e+00
 1.19673433e-06 5.25936475e-02]
