In [1]:
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression

In [2]:
import numpy as np

X = np.random.rand(100, 10)
y = np.random.randint(0, 2, 100)

gnb = GaussianNB()
log = LogisticRegression()

gnb.fit(X, y)
log.fit(X, y)

print(gnb.classes_)
print(log.classes_)

[0 1]
[0 1]


In [3]:
log.coef_

array([[-0.96481036,  0.86110111, -0.44264731, -0.0439701 , -0.76202979,
        -0.6301493 ,  0.99954298, -0.0367028 , -0.10103162,  0.03637855]])

In [5]:
X_test = np.random.rand(5, 10)
print(gnb.predict(X_test))
print(gnb.predict_proba(X_test))

[0 0 0 1 1]
[[0.60544788 0.39455212]
 [0.56790193 0.43209807]
 [0.55575952 0.44424048]
 [0.28757774 0.71242226]
 [0.34740996 0.65259004]]


In [6]:
predictions = gnb.predict_proba(X_test)
print(predictions[:, 1])

[0.39455212 0.43209807 0.44424048 0.71242226 0.65259004]


In [7]:
log.coef_

array([[-0.96481036,  0.86110111, -0.44264731, -0.0439701 , -0.76202979,
        -0.6301493 ,  0.99954298, -0.0367028 , -0.10103162,  0.03637855]])

In [8]:
np.array([np.log(predictions[:, 0] / predictions[:, 1])])[0]

array([ 0.42821722,  0.27329616,  0.22396964, -0.90717759, -0.63044362])

In [10]:
log.predict_log_proba(X_test)

array([[-0.67304041, -0.71366654],
       [-1.0505152 , -0.43040992],
       [-0.79677821, -0.59925426],
       [-0.51519353, -0.90977443],
       [-0.94746377, -0.4905707 ]])

In [25]:
X = np.random.rand(100, 10)
y = np.random.randint(0, 2, 100)

gnb = GaussianNB()

gnb.fit(X, y)

print(gnb.theta_)
print()
print(gnb.var_)
print()

X_test = np.random.rand(5, 10)
print(X_test)

print("\nConditional Probs\n")

def conditional_probability(x, mean, std):
    return np.exp(-0.5 * ((x - mean) ** 2) / (std ** 2)) / (np.sqrt(2 * np.pi) * std)

print(conditional_probability(X_test[0, :], gnb.theta_[0, 0], gnb.var_[0, 0]))

[[0.53004214 0.44708465 0.5772285  0.52274176 0.50390699 0.48649797
  0.4945376  0.5646919  0.53262547 0.50914712]
 [0.49161854 0.52833682 0.52050275 0.52508526 0.52322409 0.5401375
  0.53163477 0.50186335 0.47674483 0.50792644]]

[[0.07804228 0.06829459 0.08458729 0.08543922 0.06494068 0.07125955
  0.10554143 0.06881087 0.09282454 0.08537054]
 [0.07664163 0.08532702 0.06875575 0.08028363 0.07906187 0.0880499
  0.076577   0.09410564 0.09039013 0.06184335]]

[[0.56040104 0.23660422 0.40650353 0.48511491 0.94106846 0.19814536
  0.81058626 0.8520721  0.86032942 0.33874954]
 [0.75245561 0.73329849 0.88055436 0.45245807 0.80542254 0.39450993
  0.14975676 0.62918976 0.35922702 0.72850988]
 [0.18391521 0.11856866 0.96791553 0.43067903 0.57246134 0.82283847
  0.29775022 0.40745662 0.94233128 0.9606324 ]
 [0.13111312 0.12932039 0.52685597 0.93938593 0.15294931 0.40669514
  0.02245977 0.47788039 0.66478901 0.32163084]
 [0.3321408  0.36075061 0.00952203 0.22833911 0.04328579 0.91317336
  0.171898

In [14]:
X_test[0, :]

array([0.60979973, 0.67712346, 0.77626045, 0.62184202, 0.34563163,
       0.01554476, 0.73060221, 0.5136381 , 0.35943055, 0.30229868])

In [ ]:
cp1 = np.exp(-0.5 * ((X_test[0, :] - gnb.theta_[0, :]) ** 2) / (gnb.var_[0, :] ** 2)) / (np.sqrt(2 * np.pi) * gnb.var_[0, :])
cp2 = np.exp(-0.5 * ((X_test[0, :] - gnb.theta[1, :]) ** 2) / (gnb.var_[1, :] ** 2)) / (np.sqrt(2 * np.pi) * gnb.var_[1, :])

In [20]:
np.log(cp1/cp2)

array([ 1.48526903,  1.46305556, -2.69991304,  1.03703566,  0.19633388,
       -0.21622236,  0.701082  , -0.10587423,  1.2273245 ,  0.05313815])

In [19]:
cp2

array([7.16803320e-01, 8.11519846e-02, 1.65313827e-01, 4.87075075e-01,
       7.15134475e-01, 2.97661513e-08, 8.04867887e-02, 4.75319116e+00,
       3.30659146e-01, 6.17385938e-01])

In [22]:
log.coef_[0]

array([-0.96481036,  0.86110111, -0.44264731, -0.0439701 , -0.76202979,
       -0.6301493 ,  0.99954298, -0.0367028 , -0.10103162,  0.03637855])

In [29]:
X_test.shape

(5, 10)

In [47]:
r = np.exp(-0.5 * ((X_test[0, :] - gnb.theta_) ** 2) / (gnb.var_ ** 2)) / (np.sqrt(2 * np.pi) * gnb.var_)
r.shape

(2, 10)

In [38]:
X_test[0, :]

array([0.9843637 , 0.80743006, 0.69885443, 0.44485678, 0.73304143,
       0.3847246 , 0.63523182, 0.82765939, 0.05280199, 0.36063146])

In [40]:
gnb.theta_

array([[0.47162351, 0.52919582, 0.48608094, 0.47518494, 0.47146758,
        0.54507869, 0.49007721, 0.48705901, 0.56537715, 0.52474568],
       [0.48028192, 0.51399483, 0.4372207 , 0.53887687, 0.48488585,
        0.49438719, 0.44540864, 0.53340339, 0.55207027, 0.50061743]])

In [39]:
gnb.var_

array([[0.07393723, 0.08239409, 0.0814921 , 0.08597926, 0.10114798,
        0.07717108, 0.07462266, 0.08000971, 0.0798159 , 0.08668274],
       [0.08102462, 0.08387918, 0.07750704, 0.06797362, 0.08724462,
        0.09533437, 0.07531337, 0.1051986 , 0.08702169, 0.07760439]])

In [51]:
cp = conditional_prob(X_test, gnb.theta_, gnb.var_)
cp

[[1.94584416e-10 1.61743750e-02 1.61981431e-01 4.36011564e+00
  1.39234167e-01 5.96873079e-01 8.06144019e-01 5.78944296e-04
  5.53738803e-09 7.66682781e-01]
 [1.93905660e-08 1.04658182e-02 1.72674565e-02 2.25487994e+00
  8.00498175e-02 2.15941577e+00 2.21095247e-01 7.58460015e-02
  3.26262600e-07 1.01032473e+00]]


ValueError: could not broadcast input array from shape (2,10) into shape (10,)