In [1]:
import sys
import os

# Obtener el directorio actual
current_directory = os.getcwd()

# Subir dos niveles al directorio raíz, donde se encuentra la carpeta 'interpretml'
root_path = os.path.abspath(os.path.join(current_directory, '..', '..', '..'))

sys.path.append(root_path)

In [2]:
import pandas as pd
import numpy as np
import interpret

Read the data

In [3]:
X_train = pd.read_csv('data/X_train.csv')
y_train = pd.read_csv('data/y_train.csv').to_numpy().ravel()

X_test = pd.read_csv('data/X_test.csv')
y_test = pd.read_csv('data/y_test.csv').to_numpy().ravel()

In [4]:
from interpret.glassbox import ExplainableBoostingClassifier
from interpret import show

ebm = ExplainableBoostingClassifier(interactions=2)
ebm.fit(X_train, y_train)

ExplainableBoostingClassifier(interactions=2)

## Global explanations

In [5]:
ebm_global = ebm.explain_global()
show(ebm_global)

Utilizando librería modificada de interpret
(0, 7)
[0.0, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5, 11.5, 12.5, 13.5, 17.0]
[21.0, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5, 27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5, 38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5, 49.5, 50.5, 51.5, 52.5, 53.5, 54.5, 55.5, 56.5, 57.5, 58.5, 59.5, 60.5, 62.5, 63.5, 64.5, 65.5, 66.5, 67.5, 69.5, 81.0]
(1, 4)
[0.0, 69.5, 74.5, 78.5, 80.5, 83.5, 84.5, 87.5, 88.5, 89.5, 90.5, 91.5, 92.5, 94.5, 95.5, 98.5, 99.5, 100.5, 101.5, 102.5, 104.5, 105.5, 106.5, 108.5, 109.5, 111.5, 112.5, 114.5, 116.5, 117.5, 119.5, 121.5, 122.5, 123.5, 124.5, 125.5, 127.5, 128.5, 129.5, 131.5, 134.5, 137.5, 139.5, 141.5, 143.5, 145.5, 146.5, 148.5, 151.5, 154.5, 157.5, 158.5, 161.5, 162.5, 164.5, 167.5, 172.0, 174.5, 179.5, 182.0, 187.5, 192.5, 198.0]
[0.0, 7.0, 24.0, 36.5, 43.5, 47.0, 49.5, 53.5, 55.5, 56.5, 58.5, 63.5, 65.5, 66.5, 70.5, 73.5, 75.5, 76.5, 82.0, 87.5, 89.5, 93.0, 94.5, 

<!-- http://127.0.0.1:7001/1446966548704/ -->

EBM class use 'ebm.term_scores' to create the graph. Each term has a list of scores, each one representing a bin of the variable (or term). In the case of glucose, a low (0-120) value would mean a negative score, suggesting no-diabetes prediction; a high score (120-180) would likely mean that the person has diabetes.

The number of scores in the list is determined by the bins of the variable. And the number of bins depend on the distribution of the variable and the discretization algorithm used. For example, in the case of glucose would be the following bins:

In [6]:
print("Number of bins in glucose: ", len(ebm.bins_[1][0]))
ebm.bins_[1][0]

Number of bins in glucose:  127


array([ 22. ,  50. ,  56.5,  62. ,  67.5,  69.5,  72. ,  73.5,  74.5,
        75.5,  76.5,  77.5,  78.5,  79.5,  80.5,  81.5,  82.5,  83.5,
        84.5,  85.5,  86.5,  87.5,  88.5,  89.5,  90.5,  91.5,  92.5,
        93.5,  94.5,  95.5,  96.5,  97.5,  98.5,  99.5, 100.5, 101.5,
       102.5, 103.5, 104.5, 105.5, 106.5, 107.5, 108.5, 109.5, 110.5,
       111.5, 112.5, 113.5, 114.5, 115.5, 116.5, 117.5, 118.5, 119.5,
       120.5, 121.5, 122.5, 123.5, 124.5, 125.5, 126.5, 127.5, 128.5,
       129.5, 130.5, 131.5, 132.5, 133.5, 134.5, 135.5, 136.5, 137.5,
       138.5, 139.5, 140.5, 141.5, 142.5, 143.5, 144.5, 145.5, 146.5,
       147.5, 148.5, 149.5, 150.5, 151.5, 152.5, 153.5, 154.5, 155.5,
       156.5, 157.5, 158.5, 159.5, 160.5, 161.5, 162.5, 163.5, 164.5,
       165.5, 166.5, 167.5, 168.5, 169.5, 170.5, 172. , 173.5, 174.5,
       175.5, 176.5, 177.5, 178.5, 179.5, 180.5, 182. , 183.5, 185. ,
       186.5, 187.5, 188.5, 189.5, 190.5, 192.5, 194.5, 195.5, 196.5,
       197.5])

And the constant value associated to each bin:

In [7]:
ebm.term_scores_[1]

array([ 0.        , -0.63099025, -0.96340995, -1.07419818, -1.08696046,
       -1.09622566, -1.10274483, -1.10289811, -1.10208151, -1.09683749,
       -1.0895702 , -1.08023566, -1.06673348, -1.05791202, -1.05088763,
       -1.04238371, -1.03588866, -1.02504243, -1.01327663, -1.00053769,
       -0.99254221, -0.9866094 , -0.97700863, -0.96352772, -0.95094951,
       -0.87290783, -0.85902529, -0.82093015, -0.80191835, -0.79039522,
       -0.73511625, -0.74355387, -0.72844433, -0.72850191, -0.70666284,
       -0.58605972, -0.55097082, -0.48845591, -0.47596127, -0.43548435,
       -0.44000901, -0.42161198, -0.27850545, -0.26367686, -0.25517668,
       -0.24383747, -0.22785207, -0.2121048 , -0.20165836, -0.19118097,
       -0.17604766, -0.16344234, -0.15081739, -0.1416803 , -0.12985512,
       -0.120627  , -0.09882757, -0.08985672, -0.09918228,  0.11258764,
        0.11835203,  0.09493013,  0.10516306,  0.12794073,  0.14430878,
        0.34647529,  0.36365193,  0.37696104,  0.39750485,  0.40

So this means that we can modify the value on each bin to visualize, for example, the weights of another model:

#### 1. Constant score

In [8]:
ebm.term_scores_[1] = np.ones(ebm.term_scores_[1].shape)

In [9]:
ebm.term_scores_[1]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
ebm_global = ebm.explain_global()
show(ebm_global)

Utilizando librería modificada de interpret
(0, 7)
[0.0, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5, 11.5, 12.5, 13.5, 17.0]
[21.0, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5, 27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5, 38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5, 49.5, 50.5, 51.5, 52.5, 53.5, 54.5, 55.5, 56.5, 57.5, 58.5, 59.5, 60.5, 62.5, 63.5, 64.5, 65.5, 66.5, 67.5, 69.5, 81.0]
(1, 4)
[0.0, 69.5, 74.5, 78.5, 80.5, 83.5, 84.5, 87.5, 88.5, 89.5, 90.5, 91.5, 92.5, 94.5, 95.5, 98.5, 99.5, 100.5, 101.5, 102.5, 104.5, 105.5, 106.5, 108.5, 109.5, 111.5, 112.5, 114.5, 116.5, 117.5, 119.5, 121.5, 122.5, 123.5, 124.5, 125.5, 127.5, 128.5, 129.5, 131.5, 134.5, 137.5, 139.5, 141.5, 143.5, 145.5, 146.5, 148.5, 151.5, 154.5, 157.5, 158.5, 161.5, 162.5, 164.5, 167.5, 172.0, 174.5, 179.5, 182.0, 187.5, 192.5, 198.0]
[0.0, 7.0, 24.0, 36.5, 43.5, 47.0, 49.5, 53.5, 55.5, 56.5, 58.5, 63.5, 65.5, 66.5, 70.5, 73.5, 75.5, 76.5, 82.0, 87.5, 89.5, 93.0, 94.5, 

<!-- http://127.0.0.1:7001/1447271544336/ -->

#### 2. Random scores

In [11]:
ebm.term_scores_[1] = np.random.rand(ebm.term_scores_[1].shape[0])

In [12]:
ebm.term_scores_[1]

array([0.51387227, 0.69557619, 0.23871572, 0.53841628, 0.64323544,
       0.22507502, 0.29991239, 0.4169889 , 0.79436062, 0.86031461,
       0.65159743, 0.33740225, 0.26309045, 0.67191239, 0.80864161,
       0.33289637, 0.04189553, 0.50704678, 0.42873708, 0.30091766,
       0.47352329, 0.74296242, 0.01745356, 0.7520779 , 0.83547282,
       0.21280395, 0.70671087, 0.29420222, 0.67253608, 0.50716736,
       0.37262996, 0.65071482, 0.95805503, 0.49437837, 0.88511414,
       0.42772462, 0.64786803, 0.0912802 , 0.03724324, 0.36641439,
       0.6813123 , 0.2405457 , 0.24214237, 0.74095761, 0.51642197,
       0.82367055, 0.54959528, 0.97366664, 0.22387067, 0.97006598,
       0.01594415, 0.36192437, 0.30067808, 0.63809879, 0.18836922,
       0.46712668, 0.85164264, 0.51245509, 0.58981193, 0.61918913,
       0.77533268, 0.04040979, 0.55057723, 0.288693  , 0.53805535,
       0.02070841, 0.34052542, 0.62345539, 0.927176  , 0.73429626,
       0.45309576, 0.36814027, 0.55794529, 0.01170468, 0.86737

In [13]:
ebm_global = ebm.explain_global()
show(ebm_global)

Utilizando librería modificada de interpret
(0, 7)
[0.0, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5, 11.5, 12.5, 13.5, 17.0]
[21.0, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5, 27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5, 38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5, 49.5, 50.5, 51.5, 52.5, 53.5, 54.5, 55.5, 56.5, 57.5, 58.5, 59.5, 60.5, 62.5, 63.5, 64.5, 65.5, 66.5, 67.5, 69.5, 81.0]
(1, 4)
[0.0, 69.5, 74.5, 78.5, 80.5, 83.5, 84.5, 87.5, 88.5, 89.5, 90.5, 91.5, 92.5, 94.5, 95.5, 98.5, 99.5, 100.5, 101.5, 102.5, 104.5, 105.5, 106.5, 108.5, 109.5, 111.5, 112.5, 114.5, 116.5, 117.5, 119.5, 121.5, 122.5, 123.5, 124.5, 125.5, 127.5, 128.5, 129.5, 131.5, 134.5, 137.5, 139.5, 141.5, 143.5, 145.5, 146.5, 148.5, 151.5, 154.5, 157.5, 158.5, 161.5, 162.5, 164.5, 167.5, 172.0, 174.5, 179.5, 182.0, 187.5, 192.5, 198.0]
[0.0, 7.0, 24.0, 36.5, 43.5, 47.0, 49.5, 53.5, 55.5, 56.5, 58.5, 63.5, 65.5, 66.5, 70.5, 73.5, 75.5, 76.5, 82.0, 87.5, 89.5, 93.0, 94.5, 

<!-- http://127.0.0.1:7001/1447270725136/ -->

So in this way we can use the same visualization for models like Naive Bayes.

We could also modify the histogram values using 'ebm.histogram_edges_' and 'ebm.histogram_weights_'.

In [14]:
ebm.histogram_edges_[1]

array([  0. ,  16.5,  33. ,  49.5,  66. ,  82.5,  99. , 115.5, 132. ,
       148.5, 165. , 181.5, 198. ])

In [15]:
ebm.histogram_weights_[1]

array([  0.,   4.,   0.,   1.,   3.,  36., 103., 145., 125.,  83.,  49.,
        38.,  27.,   0.])

## Local explanations

In [16]:
ebm_local = ebm.explain_local(X_test, y_test)
show(ebm_local)

<!-- http://127.0.0.1:7001/1447270765856/ -->

In [17]:
ebm_local._internal_obj['specific'][0]['meta']

{'label_names': [0, 1]}

In [18]:
ebm.term_scores_[0].shape

(19,)

In [19]:
X_test.iloc[0]

pregnancies      1.000
glucose        199.000
diastolic       76.000
triceps         43.000
insulin          0.000
bmi             42.900
dpf              1.394
age             22.000
Name: 0, dtype: float64

In [20]:
ebm.predict_proba(X_test)

array([[0.49089266, 0.50910734],
       [0.81316633, 0.18683367],
       [0.74418489, 0.25581511],
       [0.40793982, 0.59206018],
       [0.56320325, 0.43679675],
       [0.92490385, 0.07509615],
       [0.14440811, 0.85559189],
       [0.15508264, 0.84491736],
       [0.6951339 , 0.3048661 ],
       [0.44578222, 0.55421778],
       [0.38563423, 0.61436577],
       [0.09346007, 0.90653993],
       [0.50589061, 0.49410939],
       [0.65466813, 0.34533187],
       [0.42072044, 0.57927956],
       [0.30318502, 0.69681498],
       [0.18320589, 0.81679411],
       [0.93044429, 0.06955571],
       [0.32325793, 0.67674207],
       [0.54153865, 0.45846135],
       [0.40681343, 0.59318657],
       [0.68327664, 0.31672336],
       [0.69201208, 0.30798792],
       [0.41145881, 0.58854119],
       [0.90804547, 0.09195453],
       [0.71771638, 0.28228362],
       [0.82543472, 0.17456528],
       [0.11664939, 0.88335061],
       [0.78989496, 0.21010504],
       [0.70717424, 0.29282576],
       [0.

In [21]:
scores = ebm._predict_score(X_test)
scores

array([ 0.0364334 , -1.47071692, -1.06783456,  0.37248863, -0.25417259,
       -2.51092055,  1.77915013,  1.69528068, -0.82423182,  0.21772716,
        0.46570113,  2.27210075, -0.02356351, -0.63962254,  0.31981662,
        0.83217669,  1.49477645, -2.59353417,  0.73883967, -0.16653843,
        0.37715428, -0.76887111, -0.80954283,  0.35793801, -2.29000023,
       -0.93316216, -1.55361143,  2.02454942, -1.32429241, -0.88169931,
       -0.38595106, -1.24207306, -1.16080132,  0.34776368, -3.29443645,
        0.36071822,  0.73001524, -3.2826312 , -1.06510172, -0.27647092,
       -1.15927535, -1.49997433, -0.24355246,  0.21554628, -0.08584968,
       -2.44536473, -2.64398296, -1.41702175, -0.50752235,  0.03901295,
        0.01137909, -1.10016748,  0.64247278,  0.86643225,  0.83702432,
       -2.60517476, -0.20376522, -0.20490933, -0.50226766, -1.24698748,
        0.94998374,  0.59535594, -1.71454081,  0.0253679 , -0.09622922,
        0.80921813,  0.99962358, -0.95536541,  0.7456069 ,  0.35

In [22]:
ebm_local.data(2)

{'type': 'univariate',
 'names': ['pregnancies',
  'glucose',
  'diastolic',
  'triceps',
  'insulin',
  'bmi',
  'dpf',
  'age',
  'pregnancies & age',
  'glucose & insulin'],
 'scores': [-0.04484705147183339,
  0.33740224976053845,
  -0.01568311965900504,
  -0.030176061300163523,
  0.009020029244850623,
  0.260328294298641,
  0.03824722953561576,
  -0.15562985228560677,
  -0.13939043869948706,
  -0.4173923536111542],
 'values': [4.0, 76.0, 62.0, 0.0, 0.0, 34.0, 0.391, 25.0, '', ''],
 'extra': {'names': ['Intercept'],
  'scores': [-0.9097134870884667],
  'values': [1]},
 'perf': {'is_classification': True,
  'actual': 0,
  'predicted': 0,
  'actual_score': 0.7441848911874169,
  'predicted_score': 0.7441848911874169},
 'meta': {'label_names': [0, 1]}}